src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EventRepository::class)]
class Event
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(length: 255)]
    private ?string $Heure = null;

    #[ORM\Column]
    private ?int $nbrMaxParticipants = null;

    #[ORM\Column]
    private ?bool $publique = null;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'createdEvents')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $creator = null;

    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'attendedEvents')]
    #[ORM\JoinTable(name: 'event_user')]
    private Collection $attendees;

    public function __construct()
    {
        $this->attendees = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getHeure(): ?string
    {
        return $this->Heure;
    }

    public function setHeure(string $Heure): static
    {
        $this->Heure = $Heure;

        return $this;
    }

    public function getNbrMaxParticipants(): ?int
    {
        return $this->nbrMaxParticipants;
    }

    public function setNbrMaxParticipants(int $nbrMaxParticipants): static
    {
        $this->nbrMaxParticipants = $nbrMaxParticipants;

        return $this;
    }

    public function isPublique(): ?bool
    {
        return $this->publique;
    }

    public function setPublique(bool $publique): static
    {
        $this->publique = $publique;

        return $this;
    }

    public function getCreator(): ?User
    {
        return $this->creator;
    }

    public function setCreator(?User $creator): static
    {
        $this->creator = $creator;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getAttendees(): Collection
    {
        return $this->attendees;
    }

    public function addAttendee(User $user): static
    {
        if (!$this->attendees->contains($user)) {
            $this->attendees[] = $user;
        }

        return $this;
    }

    public function removeAttendee(User $user): static
    {
        $this->attendees->removeElement($user);

        return $this;
    }

    public function getNbrAttendees(): int
    {
        return $this->attendees->count();
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text><text y=%221.3em%22 x=%220.2em%22 font-size=%2276%22 fill=%22%23fff%22>sf</text></svg>">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        

        {% block stylesheets %}
        {% endblock %}

        {% block javascripts %}
        {% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{{ path('home') }}">Accueil</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    {% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ path('event_list') }}">Mes inscriptions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ path('event_list_user') }}">Mes événements</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ path('event_new') }}">Créer événement</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ path('profil') }}">Profil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ path('edit_profil') }}">Modifier le profil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ path('logout') }}">Déconnexion</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ path('register') }}">Inscription</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ path('login') }}">Connexion</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        <div class="container">
            {% block body %}
            {% endblock %}
        </div>
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    </body>
</html>

templates/home.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion d'événements{% endblock %}
    
{% block body %}
    <h1 class="my-4">Tous les événements</h1>

    {{ form_start(form) }}
        <div class="form-row">
            <div class="col">
                {{ form_row(form.titre) }}
            </div>
            <div class="col">
                {{ form_row(form.date) }}
            </div>
            <div class="col">
                <button type="submit" class="btn btn-primary">Filtrer</button>
            </div>
        </div>
    {{ form_end(form) }}

        <div class="row mt-2">
            {% for event in pagination.items %}
                {% if event.publique or is_granted('IS_AUTHENTICATED_FULLY') %}
                    <div class="col-md-4 mb-4">
                        <div class="card h-100">
                            <div class="card-body d-flex flex-column">
                                <h5 class="card-title">{{ event.titre }}</h5>
                                <p class="card-text">{{ event.description }}</p>
                                <p class="card-text">Le {{event.date|date('d-m-Y')}} à {{ event.heure }}h</p>
                                <p class="card-text">Nombre de personnes maximum :  {{ event.nbrMaxParticipants }}</p>
                                <p class="card-text">Nombre de personnes inscrites :  {{ event.nbrAttendees }}</p>
                                <p class="card-text">Publique : {{ event.publique ? 'Oui' : 'Non' }}</p>
                                <p class="card-text">Créateur : {{ event.creator.nom }} {{ event.creator.prenom }}</p>
                                <a href="{{ path('event_show', {'id': event.id}) }}" class="btn btn-info mb-1">Détails</a>

                                {% if is_granted('edit', event) %}
                                    <a href="{{ path('event_edit', {'id': event.id}) }}" class="btn btn-warning mb-1">Modifier</a>
                                    
                                    <form action="{{ path('event_delete', {'id': event.id}) }}" method="post" onsubmit="return confirm('Voulez-vous vraiment supprimer cet événement ?');" style="display:inline;">
                                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ event.id) }}">
                                        <button class="btn btn-danger mb-1 w-100">Supprimer</button>
                                    </form>

                                {% endif %}

                                {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                                    {% if event.attendees.contains(app.user) %}
                                        <a href="{{ path('event_unsubscribe', {'id': event.id}) }}" class="btn btn-dark ">Se désinscrire</a>
                                    {% else %}
                                        <a href="{{ path('event_subscribe', {'id': event.id}) }}" class="btn btn-success">S'inscrire</a>
                                    {% endif %}
                                {% else %}
                                    <p><a href="{{ path('login') }}">Se connecter</a> pour s'inscrire à cet événement.</p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        <div class="pagination">
            {{ knp_pagination_render(pagination) }}
        </div>
{% endblock %}